### ISSUE TITLE
[image_picker] 이미지 등록 서버 연동 (CRUD)

### ISSUE THREAD

**Issue by koba0909** [mash-up-kr/Potato-Invitation-Android#78]
- [x] 이미지 서버 등록

- [ ] 이미지 수정

- [x] 이미지 제거

**Comment by dlwls5201** [comment]
삭제 기능이 있으면 좋을것 같습니다.

**Comment by dlwls5201** [comment]
카메라 기능 추가 할꺼면 개인정보 처리 방침 작업 부탁드립니다.

https://layers7.tistory.com/39

**Comment by dlwls5201** [comment]
사진 받아 올 때 screenshots 등 다른 경로의 폴더에 있는 것은 error가 발생합니다. 

/storage/emulated/0/DCIM/Screenshots/SmartSelect_20201112-150044_KB%20Starbanking.jpg: open failed: ENOENT (No such file or directory)

**Comment by dlwls5201** [comment]
사진 경로 관련 발생 에러 제가 확인하겠습니다.

**Comment by dlwls5201** [comment]
오래된 이슈이므로 제가 닫겠습니다. 추후 수정 및 삭제 기능 작업해 주세요.
