### ISSUE TITLE
[view]리스트 화면 추가

### ISSUE THREAD

**Issue by godjoy** [mash-up-kr/Potato-Invitation-Android#93]
- [x] 리스트화면 추가하기

- [x] 최근 초대장이 앞에 오도록 수정하기

**Comment by dlwls5201** [comment]
https://github.com/mash-up-kr/Potato-Invitation-Android/issues/94
완료되면 작업해 주세요! 리스트 화면 디자인 나오기 전까지 완료하겠습니다.

**Comment by dlwls5201** [comment]
1. 초대장이 없을때 화면 추가해주세요.
2. 최근 초대장이 앞에 오도록 수정되면 좋겠는데 어떤가요?
